In [1]:
import pandas as pd
import numpy as np

In [66]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [2]:
xl_file = pd.ExcelFile('Dataset.xlsx')

In [4]:
dfs = {sheet_name: xl_file.parse(sheet_name) 
          for sheet_name in xl_file.sheet_names}

In [76]:
customers = pd.read_excel('Dataset.xlsx',
sheetname=0,
header=0,
index_col=False,
keep_default_na=True
)

/anaconda3/lib/python3.6/site-packages/pandas/io/excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)


In [3]:
customers.columns

Index(['Month', 'WeekOfMonth', 'DayOfWeek', 'Make', 'AccidentArea',
       'DayOfWeekClaimed', 'MonthClaimed', 'WeekOfMonthClaimed', 'Sex',
       'MaritalStatus', 'Age', 'Fault', 'PolicyType', 'VehicleCategory',
       'VehiclePrice', 'FraudFound_P', 'PolicyNumber', 'RepNumber',
       'Deductible', 'DriverRating', 'Days_Policy_Accident',
       'Days_Policy_Claim', 'PastNumberOfClaims', 'AgeOfVehicle',
       'AgeOfPolicyHolder', 'PoliceReportFiled', 'WitnessPresent', 'AgentType',
       'NumberOfSuppliments', 'AddressChange_Claim', 'NumberOfCars', 'Year',
       'BasePolicy', 'ClaimSize'],
      dtype='object')

In [4]:
customers.head()

Month  WeekOfMonth  DayOfWeek    Make AccidentArea DayOfWeekClaimed  \
0   Dec            5  Wednesday   Honda        Urban          Tuesday   
1   Jan            3  Wednesday   Honda        Urban           Monday   
2   Oct            5     Friday   Honda        Urban         Thursday   
3   Jun            2   Saturday  Toyota        Rural           Friday   
4   Feb            1   Saturday   Honda        Urban           Monday   

  MonthClaimed  WeekOfMonthClaimed     Sex MaritalStatus      ...       \
0          Jan                   1  Female        Single      ...        
1          Jan                   4    Male        Single      ...        
2          Nov                   2    Male       Married      ...        
3          Jul                   1    Male       Married      ...        
4          Feb                   3    Male       Married      ...        

   AgeOfPolicyHolder PoliceReportFiled WitnessPresent AgentType  \
0           26 to 30                No             No  External   
1           31 to 35               Yes             No  External   
2           41 to 50                No             No  External   
3           51 to 65               Yes             No  External   
4           36 to 40                No             No  External   

  NumberOfSuppliments  AddressChange_Claim  NumberOfCars  Year  BasePolicy  \
0                none               1 year        3 to 4  1994   Liability   
1                none            no change     1 vehicle  1994   Collision   
2                none            no change     1 vehicle  1994   Collision   
3         more than 5            no change     1 vehicle  1994   Liability   
4              1 to 2            no change     1 vehicle  1994   Collision   

      ClaimSize  
0  55526.069421  
1  59294.455571  
2  71756.941320  
3   7584.153493  
4  98545.374339  

[5 rows x 34 columns]

In [94]:
customers['DayOfWeekClaimed'].value_counts()

Monday       2811
Tuesday      2545
Wednesday    2232
Thursday     2000
Friday       1842
Saturday       94
Sunday         40
0               1
Name: DayOfWeekClaimed, dtype: int64

In [5]:
## Price more than 69000
X=customers[customers['VehiclePrice'] =='more than 69000']['FraudFound_P'].values
Fraud=len(np.where(X==1)[0])
NotFraud=len(np.where(X==0)[0])
TotalClaims=len(X)
print('Fraud',Fraud)
print('Not Fraud',NotFraud)
print('Total Claims',TotalClaims)
## Percentage of fraud claim
print('Fraud',(Fraud/TotalClaims)*100,'%')
print('Not Fraud',(NotFraud/TotalClaims)*100,'%')

Fraud 142
Not Fraud 1463
Total Claims 1605
Fraud 8.847352024922118 %
Not Fraud 91.15264797507788 %


In [6]:
## Checking the witness present and price more than 69000
X=customers[customers['VehiclePrice'] =='more than 69000']
X=X[X['WitnessPresent']=='Yes']['FraudFound_P'].values
Fraud=len(np.where(X==1)[0])
NotFraud=len(np.where(X==0)[0])
TotalClaims=len(X)
print('Fraud',Fraud)
print('Not Fraud',NotFraud)
print('Total Claims',TotalClaims)
## Percentage of fraud claim
print('Fraud',(Fraud/TotalClaims)*100,'%')
print('Not Fraud',(NotFraud/TotalClaims)*100,'%')

Fraud 0
Not Fraud 14
Total Claims 14
Fraud 0.0 %
Not Fraud 100.0 %


In [7]:
## Checking the police report present and price more than 69000
X=customers[customers['VehiclePrice'] =='more than 69000']
X=X[X['PoliceReportFiled']=='Yes']['FraudFound_P'].values
Fraud=len(np.where(X==1)[0])
NotFraud=len(np.where(X==0)[0])
TotalClaims=len(X)
print('Fraud',Fraud)
print('Not Fraud',NotFraud)
print('Total Claims',TotalClaims)
## Percentage of fraud claim
print('Fraud',(Fraud/TotalClaims)*100,'%')
print('Not Fraud',(NotFraud/TotalClaims)*100,'%')

Fraud 2
Not Fraud 45
Total Claims 47
Fraud 4.25531914893617 %
Not Fraud 95.74468085106383 %


In [17]:
X=customers[customers['VehiclePrice'] =='more than 69000']
X=X[X['AccidentArea']=='Rural']['FraudFound_P'].values
Fraud=len(np.where(X==1)[0])
NotFraud=len(np.where(X==0)[0])
TotalClaims=len(X)
print('Fraud',Fraud)
print('Not Fraud',NotFraud)
print('Total Claims',TotalClaims)
## Percentage of fraud claim
print('Fraud',(Fraud/TotalClaims)*100,'%')
print('Not Fraud',(NotFraud/TotalClaims)*100,'%')

Fraud 19
Not Fraud 150
Total Claims 169
Fraud 11.242603550295858 %
Not Fraud 88.75739644970415 %


In [19]:
X=customers[customers['AccidentArea']=='Urban']['FraudFound_P'].values
Fraud=len(np.where(X==1)[0])
NotFraud=len(np.where(X==0)[0])
TotalClaims=len(X)
print('Fraud',Fraud)
print('Not Fraud',NotFraud)
print('Total Claims',TotalClaims)
## Percentage of fraud claim
print('Fraud',(Fraud/TotalClaims)*100,'%')
print('Not Fraud',(NotFraud/TotalClaims)*100,'%')

Fraud 587
Not Fraud 9769
Total Claims 10356
Fraud 5.668211664735419 %
Not Fraud 94.33178833526458 %


In [40]:
X=customers[customers['Sex'] =='Male']
X=X[X['MaritalStatus']=='Single']['FraudFound_P'].values
Fraud=len(np.where(X==1)[0])
NotFraud=len(np.where(X==0)[0])
TotalClaims=len(X)
print('Fraud',Fraud)
print('Not Fraud',NotFraud)
print('Total Claims',TotalClaims)
## Percentage of fraud claim
print('Fraud',(Fraud/TotalClaims)*100,'%')
print('Not Fraud',(NotFraud/TotalClaims)*100,'%')

Fraud 172
Not Fraud 2551
Total Claims 2723
Fraud 6.316562614763129 %
Not Fraud 93.68343738523687 %


In [103]:
X=customers[customers['DayOfWeekClaimed'] =='Friday']['FraudFound_P'].values
Fraud=len(np.where(X==1)[0])
NotFraud=len(np.where(X==0)[0])
TotalClaims=len(X)
print('Fraud',Fraud)
print('Not Fraud',NotFraud)
print('Total Claims',TotalClaims)
## Percentage of fraud claim
print('Fraud',(Fraud/TotalClaims)*100,'%')
print('Not Fraud',(NotFraud/TotalClaims)*100,'%')

Fraud 128
Not Fraud 1714
Total Claims 1842
Fraud 6.948968512486428 %
Not Fraud 93.05103148751357 %


In [110]:
X=customers[customers['WitnessPresent'] =='Yes']['FraudFound_P'].values
Fraud=len(np.where(X==1)[0])
NotFraud=len(np.where(X==0)[0])
TotalClaims=len(X)
print('Fraud',Fraud)
print('Not Fraud',NotFraud)
print('Total Claims',TotalClaims)
## Percentage of fraud claim
print('Fraud',(Fraud/TotalClaims)*100,'%')
print('Not Fraud',(NotFraud/TotalClaims)*100,'%')

Fraud 2
Not Fraud 66
Total Claims 68
Fraud 2.941176470588235 %
Not Fraud 97.05882352941177 %


In [113]:
X=customers[customers['WitnessPresent'] =='Yes']
X=X[X['PoliceReportFiled']=='Yes']

In [115]:
X['FraudFound_P']

1182     0
1504     0
1802     0
1933     0
2064     0
2074     0
2347     0
2881     0
3002     0
3794     0
3888     0
4693     0
4897     0
6403     0
7037     0
7113     0
7241     0
7320     0
8285     0
8346     0
8824     0
9339     0
9478     0
10330    0
10568    0
10604    0
Name: FraudFound_P, dtype: int64

In [61]:
X=customers[customers['FraudFound_P']==1]['FraudFound_P'].values
len(X)

685

In [62]:
X=customers[customers['FraudFound_P']==0]['FraudFound_P'].values
len(X)

10880

In [6]:
customers.shape

(11565, 34)

In [63]:
Y=customers['FraudFound_P'].values

In [64]:
del customers['FraudFound_P']

In [30]:
### Analysis the data

In [31]:
np.unique(customers['BasePolicy'])

array(['All Perils', 'Collision', 'Liability'], dtype=object)

In [27]:
np.unique(customers['AccidentArea'])

array(['Rural', 'Urban'], dtype=object)

In [28]:
np.unique(customers['MaritalStatus'])

array(['Divorced', 'Married', 'Single', 'Widow'], dtype=object)

In [29]:
np.unique(customers['Fault'])

array(['Policy Holder', 'Third Party'], dtype=object)

In [33]:
np.unique(customers['PolicyType'])

array(['Sedan - All Perils', 'Sedan - Collision', 'Sedan - Liability',
       'Sport - All Perils', 'Sport - Collision', 'Sport - Liability',
       'Utility - All Perils', 'Utility - Collision',
       'Utility - Liability'], dtype=object)

In [34]:
np.unique(customers['VehicleCategory'])

array(['Sedan', 'Sport', 'Utility'], dtype=object)

In [37]:
np.unique(customers['VehiclePrice'])

array(['20000 to 29000', '30000 to 39000', '40000 to 59000',
       '60000 to 69000', 'less than 20000', 'more than 69000'],
      dtype=object)

In [43]:
np.unique(customers['RepNumber'])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [44]:
np.unique(customers['Deductible'])

array([300, 400, 500, 700])

In [45]:
np.unique(customers['DriverRating'])

array([ 1.,  2.,  3.,  4., nan, nan, nan, nan, nan, nan])

In [46]:
np.unique(customers['Days_Policy_Accident'])

array(['1 to 7', '15 to 30', '8 to 15', 'more than 30', 'none'],
      dtype=object)

In [48]:
np.unique(customers['Days_Policy_Claim'])

array(['15 to 30', '8 to 15', 'more than 30', 'none'], dtype=object)

In [50]:
customers['PastNumberOfClaims'].value_counts()

2 to 4         4140
none           3286
1              2675
more than 4    1464
Name: PastNumberOfClaims, dtype: int64

In [51]:
customers['AgeOfVehicle'].value_counts()

7 years        4388
more than 7    2993
6 years        2581
5 years         990
new             285
4 years         176
3 years         100
2 years          52
Name: AgeOfVehicle, dtype: int64

In [52]:
customers['AgeOfPolicyHolder'].value_counts()

31 to 35    4199
36 to 40    3008
41 to 50    2122
51 to 65    1070
26 to 30     445
over 65      388
16 to 17     247
21 to 25      73
18 to 20      13
Name: AgeOfPolicyHolder, dtype: int64

In [54]:
customers['PoliceReportFiled'].value_counts()

No     11235
Yes      330
Name: PoliceReportFiled, dtype: int64

In [55]:
customers['WitnessPresent'].value_counts()

No     11497
Yes       68
Name: WitnessPresent, dtype: int64

In [56]:
customers['AgentType'].value_counts()

External    11394
Internal      171
Name: AgentType, dtype: int64

In [57]:
customers['NumberOfSuppliments'].value_counts()

none           5330
more than 5    2875
1 to 2         1846
3 to 5         1514
Name: NumberOfSuppliments, dtype: int64

In [58]:
customers['AddressChange_Claim'].value_counts()

no change         10715
4 to 8 years        496
2 to 3 years        222
1 year              128
under 6 months        4
Name: AddressChange_Claim, dtype: int64

In [59]:
customers['NumberOfCars'].value_counts()

1 vehicle      10698
2 vehicles       559
3 to 4           288
5 to 8            19
more than 8        1
Name: NumberOfCars, dtype: int64

In [60]:
customers['Year'].value_counts()

1994    4596
1995    3923
1996    3046
Name: Year, dtype: int64

In [72]:
X=customers.values

In [69]:
Y.shape

(11565,)

In [73]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=0)